FORMAT: 1A

# Oral Cancer Detect API
Oral Cancer Detetec API.

# Group Locais de Atendimento

## Locais de Atendimento [/locaisDeAtendimento]

### Obter Locais de Atendimento [GET]
+ Response 200 (application/json)
    + Attributes (array[LocalDeAtendimento])
+ Response 401 (application/json)
    { "message": "Não autorizado" }
+ Response 404 (application/json)
    { "message": "O servidor não pode encontrar o recurso solicitado."}

## Locais de Atendimento por região [/locaisDeAtendimento/{regiao}]

### Obter Locais de Atendimento por região [GET]
+ Parameters
    + regiao (string) - Região de um local de atendimento.
+ Response 200 (application/json)
    + Attributes (array[LocalDeAtendimento])
+ Response 401 (application/json)
    { "message": "Não autorizado" }
+ Response 404 (application/json)
    { "message": "O servidor não pode encontrar o recurso solicitado."}

# Group Fatores de Risco

## Fatores de Risco [/fatoresDeRisco]

### Obter Fatores de Risco [GET]
+ Response 200 (application/json)
    + Attributes (array[FatorDeRisco])
+ Response 401 (application/json)
    { "message": "Não autorizado" }
+ Response 404 (application/json)
    { "message": "O servidor não pode encontrar o recurso solicitado."}
    
# Group Lesões

## Lesões [/lesoes]

### Obter Lesões [GET]
+ Response 200 (application/json)
    + Attributes (array[Lesao])
+ Response 401 (application/json)
    { "message": "Não autorizado" }
+ Response 404 (application/json)
    { "message": "O servidor não pode encontrar o recurso solicitado."}

# Group Rastreamento

## Rastreamentos [/rastreamentos]

### Criar Rastreamento [POST]
+ Parameters
    + [Rastreamento]

# Data Structures

## LocalDeAtendimento
+ id (string)
+ nome (string) - Nome do Local de Atendimento
+ tipo (string) - Tipo do Local de Atendimento
+ regiao (string) - Região do Local de Atendimento
+ bairro (string) - Bairro do Local de Atendimento
+ cidade (string) - Cidade do Local de Atendimento

## FatorDeRisco
+ id (string)
+ nome (string) - Nome do Local de Atendimento

## Lesao
+ id (string)
+ nome (string) - Nome do Local de Atendimento

## Paciente
+ id (string)
+ nomePaciente (string)
+ regiao (string)
+ ultimaData (string)
+ ultimoProcedimento (string)
+ status (string)

## Rastreamento
+ id (string);
+ nomePaciente (string);
+ nomeMae (string);
+ bairro (string);
+ cidade (string);
+ dataNascimento;
+ sexo (string);
+ cpf (string);
+ email (string);
+ LocalDeAtendimento;
+ FatorDeRisco;
+ Lesao;
+ dataRetornoSugerido;
+ dataSugeridaRetorno;